{% set name = "google-cloud-recommendations-ai" %}
{% set version = "0.10.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/google_cloud_recommendations_ai-{{ version }}.tar.gz
  sha256: 7b5fa821a2145b38bc0ec4f2445de85f954a889624ed15568cc35293835932f6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - google-api-core >=1.34.0,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,!=2.10.*
    - google-api-core-grpc
    - google-auth >=2.14.1,<3.0.0dev,!=2.24.0,!=2.25.0
    # more restrictive version for python >= 3.13
    - proto-plus >=1.25.0,<2.0.0dev
    - protobuf >=3.20.2,<6.0.0dev,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5

test:
  imports:
    - google
    - google.cloud
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/googleapis/google-cloud-python/tree/main/packages/google-cloud-recommendations-ai
  summary: Google Cloud Recommendations Ai API client library
  license: Apache-2.0
  license_file: LICENSE
  description: |
    Cloud Recommendations AI API: Deliver highly personalized product
    recommendations at scale.
  dev_url: https://github.com/googleapis/google-cloud-python/tree/main/packages/google-cloud-recommendations-ai
  doc_url: https://googleapis.dev/python/recommendationengine/latest/index.html

extra:
  recipe-maintainers:
    - xylar
